### ISSUE TITLE
There is something wrong with euddraft 0.8.9.4

### ISSUE THREAD

**Issue by boermyth** [armoha/euddraft#1] opened 2019-11-05 19:53 UTC
EUD.Editor2.0.17.9.7 + euddraft 0.8.9.4

1. Graphic (Unit Picture Properties): In SC x64, I has just changed a unit and other units not, but some other units' graphics will change automatically. But in SC x86 (32), it will be correctly.

2. DisplayCText: First, I use a 11-line text such as "\n\n\n\n\n\n\n\n\n\nText Test",when the game has no any other human player, it will display in line 1 correctly, but if it has two players at least, this text will display two line in line 1 and 11. And Second, for example, the player 1 can see the DisplayCText of player 2 (only for player 2).

By the way，the two bugs didn't exist before. And I didn't change the map.

Thank you for your good jod, we like this EUD and hope it will be better and better.

**Comment by boermyth** [comment] 2019-11-05 21:00
If it can't be compatible with 32-bit and 64 bit, the 64 bit is recommended, because the 64 bit is default in SCR.

**Comment by armoha** [comment] 2019-11-06 00:47
1. What kind of graphic did you change? Could you clarify how did you change so I can reproduce it.

2. Thanks for reporting it! I'll be working on this issue.

**Comment by armoha** [comment] 2019-11-06 01:54
11-line text bug will be fixed in next euddraft release.
![fixed](https://i.imgur.com/moNza3F.png)

**Comment by armoha** [comment] 2019-11-06 02:59
1. 64bit SC have had graphic bug since it was introduced, before being default settings in SCR. 64bit graphic bug is related to SCR patch, not a EUD Editor nor euddraft issue. So you should report this to Blizzard.

Below is example map, change Marine wireframe to Ghost, Ghost to Vulture, SCV to Wraith. It didn't use euddraft and only used map triggers with TrigEditPlus. I didn't change barracks wireframe though, but in 64bits, barracks wireframe is changed to Dark Templar, which is bug.
![64bits_wireframe_glitch](https://i.imgur.com/PZB1tNz.png)
```lua
-- This text is generated by TrigEditPlus

Trigger {
	players = {P1},
	conditions = {
		Switch("Switch 1", Cleared);
	},
	actions = {
		SetMemory(0x6509B0, SetTo, EPD(0));
	}
}
for i = 31, 2, -1 do
Trigger {
	players = {P1},
	conditions = {
		Switch("Switch 1", Cleared);
		MemoryX(0x68C204, AtLeast, 1, 2^i)
	},
	actions = {
		SetMemory(0x6509B0, Add, 2^(i-2));
	}
}
end
Trigger {
	players = {P1},
	conditions = {
		Switch("Switch 1", Cleared);
	},
	actions = {
		SetMemory(0x6509B0, Add, 1);
		SetDeaths(CurrentPlayer, SetTo, 34013248, 0);
		SetMemory(0x6509B0, Add, 1);
		SetDeaths(CurrentPlayer, SetTo, 239549486, 0);
		SetMemory(0x6509B0, Add, 1);
		SetDeaths(CurrentPlayer, SetTo, 100663296, 0);
		SetMemory(0x6509B0, Add, 1);
		SetDeaths(CurrentPlayer, SetTo, 328152384, 0);
		SetMemory(0x6509B0, Add, 1);
		SetDeaths(CurrentPlayer, SetTo, 100663296, 0);
		SetMemory(0x6509B0, Add, 10);
		SetDeaths(CurrentPlayer, SetTo, 117440512, 0);
		SetMemory(0x6509B0, Add, 1);
		SetDeaths(CurrentPlayer, SetTo, 883897408, 0);
		SetMemory(0x6509B0, Add, 1);
		SetDeaths(CurrentPlayer, SetTo, 117440512, 0);
		SetMemory(0x6509B0, SetTo, 0);
		SetSwitch("Switch 1", Set);
	}
}
```

**Comment by armoha** [comment] 2019-11-12 15:07
euddraft 0.8.9.5 Released, fix 11-line text bug.

**Closed as completed by armoha** 2019-11-12 15:07 UTC
Labels: bug
